# Average Number of Days an Adult is Mentally Unhealthy in the U.S.

Cameron Stevens - DATA 213 Final Project

# Dataset

Dataset: U.S._Chronic_Disease_Indicators.csv

Description: This dataset comes from CDC's Division of Population Health and contains chronic disease information for U.S. states and territories. The dataset contains overall information and information relating to sex, race/ethnicity, and age at a state/territory level.

Summary Statistics: This dataset contains summary statistics for the proportion, crude rate per 100,000, or number of people with a certain chronic illness.

Data Types: The Dataset uses interger values for the years, string values for topics, questions, and categorys, and uses doubles for data values

Source: https://catalog.data.gov/dataset/u-s-chronic-disease-indicators?from_hint=eyJzb3J0IjoicG9wdWxhcml0eSJ9

# Loading Data

In [1]:
import pandas as pd
import requests
import folium

In [2]:
# Makes it so Datasets of 200 or less rows can display the whole set
pd.options.display.max_rows = 200

In [3]:
# Read in data
diseaseDF = pd.read_csv('U.S._Chronic_Disease_Indicators.csv', delimiter=",", encoding='utf-8')

In [4]:
# Display glimpse of data
diseaseDF

        YearStart  YearEnd LocationAbbr  ... StratificationID2 StratificationCategoryID3 StratificationID3
0            2020     2020           US  ...               NaN                       NaN               NaN
1            2015     2019           AR  ...               NaN                       NaN               NaN
2            2015     2019           CA  ...               NaN                       NaN               NaN
3            2015     2019           CO  ...               NaN                       NaN               NaN
4            2015     2019           GA  ...               NaN                       NaN               NaN
...           ...      ...          ...  ...               ...                       ...               ...
309210       2022     2022           VI  ...               NaN                       NaN               NaN
309211       2022     2022           WV  ...               NaN                       NaN               NaN
309212       2022     2022           WI  ...               NaN                       NaN               NaN
309213       2022     2022           VT  ...               NaN                       NaN               NaN
309214       2022     2022           WA  ...               NaN                       NaN               NaN

[309215 rows x 34 columns]

# Cleaning Data

In [5]:
# Drop N/a columns
diseaseDF = diseaseDF.drop(columns = ['Response', 'DataValueFootnoteSymbol', 'DataValueFootnote',\
'StratificationCategory2', 'Stratification2','StratificationCategory3', 'Stratification3',\
'ResponseID', 'StratificationCategoryID2', 'StratificationID2', 'StratificationCategoryID3', 'StratificationID3'])

# Data Analysis

- Overall Data

In [6]:
# Filter to show overall mean in the year 2022
mentalHealthDF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Overall')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthDF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
261755       2022     2022           DC  ...         CRDMEAN                   OVERALL               OVR
262093       2022     2022           GA  ...         CRDMEAN                   OVERALL               OVR
263333       2022     2022           HI  ...         CRDMEAN                   OVERALL               OVR
263860       2022     2022           AL  ...         CRDMEAN                   OVERALL               OVR
264216       2022     2022           DE  ...         CRDMEAN                   OVERALL               OVR
265422       2022     2022           CT  ...         CRDMEAN                   OVERALL               OVR
266485       2022     2022           AZ  ...         CRDMEAN                   OVERALL               OVR
267378       2022     2022           GU  ...         CRDMEAN                   OVERALL               OVR
267893       2022     2022           FL  ...         CRDMEAN                   OVERALL               OVR
268832       2022     2022           CA  ...         CRDMEAN                   OVERALL               OVR
269165       2022     2022           AK  ...         CRDMEAN                   OVERALL               OVR
272416       2022     2022           AR  ...         CRDMEAN                   OVERALL               OVR
275014       2022     2022           CO  ...         CRDMEAN                   OVERALL               OVR
275558       2022     2022           NV  ...         CRDMEAN                   OVERALL               OVR
275673       2022     2022           MT  ...         CRDMEAN                   OVERALL               OVR
276296       2022     2022           IN  ...         CRDMEAN                   OVERALL               OVR
277129       2022     2022           MS  ...         CRDMEAN                   OVERALL               OVR
277488       2022     2022           KY  ...         CRDMEAN                   OVERALL               OVR
277497       2022     2022           MA  ...         CRDMEAN                   OVERALL               OVR
279492       2022     2022           MN  ...         CRDMEAN                   OVERALL               OVR
279680       2022     2022           MI  ...         CRDMEAN                   OVERALL               OVR
280854       2022     2022           ID  ...         CRDMEAN                   OVERALL               OVR
281131       2022     2022           LA  ...         CRDMEAN                   OVERALL               OVR
281848       2022     2022           MD  ...         CRDMEAN                   OVERALL               OVR
281886       2022     2022           IL  ...         CRDMEAN                   OVERALL               OVR
282905       2022     2022           IA  ...         CRDMEAN                   OVERALL               OVR
283679       2022     2022           ME  ...         CRDMEAN                   OVERALL               OVR
287020       2022     2022           NE  ...         CRDMEAN                   OVERALL               OVR
287834       2022     2022           KS  ...         CRDMEAN                   OVERALL               OVR
288878       2022     2022           MO  ...         CRDMEAN                   OVERALL               OVR
289563       2022     2022           RI  ...         CRDMEAN                   OVERALL               OVR
289704       2022     2022           OH  ...         CRDMEAN                   OVERALL               OVR
290228       2022     2022           US  ...         CRDMEAN                   OVERALL               OVR
292168       2022     2022           PR  ...         CRDMEAN                   OVERALL               OVR
293314       2022     2022           SD  ...         CRDMEAN                   OVERALL               OVR
293772       2022     2022           NC  ...         CRDMEAN                   OVERALL               OVR
294905       2022     2022           NJ  ...         CRDMEAN                   OVERALL               OVR
296099       2022     2022           NY  ...         CRDMEAN                   OVERALL               OVR
296123       2022     2022           OK  ...         CRDMEAN                   OVERALL               OVR
297473       2022     2022           NH  ...         CRDMEAN                   OVERALL               OVR
298183       2022     2022           TX  ...         CRDMEAN                   OVERALL               OVR
298948       2022     2022           PA  ...         CRDMEAN                   OVERALL               OVR
300466       2022     2022           SC  ...         CRDMEAN                   OVERALL               OVR
300903       2022     2022           OR  ...         CRDMEAN                   OVERALL               OVR
301424       2022     2022           TN  ...         CRDMEAN                   OVERALL               OVR
301873       2022     2022           ND  ...         CRDMEAN                   OVERALL               OVR
302370       2022     2022           UT  ...         CRDMEAN                   OVERALL               OVR
302613       2022     2022           NM  ...         CRDMEAN                   OVERALL               OVR
303980       2022     2022           WI  ...         CRDMEAN                   OVERALL               OVR
304020       2022     2022           WY  ...         CRDMEAN                   OVERALL               OVR
304529       2022     2022           WA  ...         CRDMEAN                   OVERALL               OVR
305438       2022     2022           WV  ...         CRDMEAN                   OVERALL               OVR
305745       2022     2022           VI  ...         CRDMEAN                   OVERALL               OVR
308080       2022     2022           VA  ...         CRDMEAN                   OVERALL               OVR
308795       2022     2022           VT  ...         CRDMEAN                   OVERALL               OVR

[55 rows x 22 columns]

In [ ]:
state_geo = requests.get( # load in map file
    "https://raw.githubusercontent.com/python-visualization/folium-example-data/main/us_states.json"
).json()
state_data = mentalHealthDF # store filtered data

m = folium.Map(location=[48, -102], zoom_start=3) # Create map object

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"], # columns we are matching and displaying
    key_on="feature.id",
    fill_color="YlGn",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among adults in the U.S.",
).add_to(m)

folium.LayerControl().add_to(m)

m # Display map

- Data for Male Adults

In [ ]:
# Filter to show mean for males in the year 2022
mentalHealthMaleDF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Male')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthMaleDF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
262298       2022     2022           GA  ...         CRDMEAN                       SEX              SEXM
262545       2022     2022           AK  ...         CRDMEAN                       SEX              SEXM
263363       2022     2022           FL  ...         CRDMEAN                       SEX              SEXM
264801       2022     2022           CO  ...         CRDMEAN                       SEX              SEXM
266618       2022     2022           DC  ...         CRDMEAN                       SEX              SEXM
267380       2022     2022           GU  ...         CRDMEAN                       SEX              SEXM
267433       2022     2022           CT  ...         CRDMEAN                       SEX              SEXM
268175       2022     2022           AZ  ...         CRDMEAN                       SEX              SEXM
269419       2022     2022           HI  ...         CRDMEAN                       SEX              SEXM
271102       2022     2022           CA  ...         CRDMEAN                       SEX              SEXM
271267       2022     2022           AL  ...         CRDMEAN                       SEX              SEXM
272351       2022     2022           AR  ...         CRDMEAN                       SEX              SEXM
274069       2022     2022           DE  ...         CRDMEAN                       SEX              SEXM
276545       2022     2022           MI  ...         CRDMEAN                       SEX              SEXM
276690       2022     2022           LA  ...         CRDMEAN                       SEX              SEXM
276939       2022     2022           MO  ...         CRDMEAN                       SEX              SEXM
277199       2022     2022           MA  ...         CRDMEAN                       SEX              SEXM
279320       2022     2022           MD  ...         CRDMEAN                       SEX              SEXM
279442       2022     2022           ME  ...         CRDMEAN                       SEX              SEXM
280702       2022     2022           MS  ...         CRDMEAN                       SEX              SEXM
281780       2022     2022           MN  ...         CRDMEAN                       SEX              SEXM
282100       2022     2022           KS  ...         CRDMEAN                       SEX              SEXM
283349       2022     2022           IN  ...         CRDMEAN                       SEX              SEXM
284856       2022     2022           NE  ...         CRDMEAN                       SEX              SEXM
285017       2022     2022           IL  ...         CRDMEAN                       SEX              SEXM
285740       2022     2022           NV  ...         CRDMEAN                       SEX              SEXM
286383       2022     2022           IA  ...         CRDMEAN                       SEX              SEXM
287484       2022     2022           MT  ...         CRDMEAN                       SEX              SEXM
287589       2022     2022           KY  ...         CRDMEAN                       SEX              SEXM
289040       2022     2022           ID  ...         CRDMEAN                       SEX              SEXM
289596       2022     2022           OR  ...         CRDMEAN                       SEX              SEXM
291270       2022     2022           NJ  ...         CRDMEAN                       SEX              SEXM
291574       2022     2022           RI  ...         CRDMEAN                       SEX              SEXM
294346       2022     2022           PR  ...         CRDMEAN                       SEX              SEXM
294532       2022     2022           NM  ...         CRDMEAN                       SEX              SEXM
296269       2022     2022           TX  ...         CRDMEAN                       SEX              SEXM
296673       2022     2022           TN  ...         CRDMEAN                       SEX              SEXM
296830       2022     2022           SC  ...         CRDMEAN                       SEX              SEXM
296969       2022     2022           OK  ...         CRDMEAN                       SEX              SEXM
297485       2022     2022           ND  ...         CRDMEAN                       SEX              SEXM
298279       2022     2022           NY  ...         CRDMEAN                       SEX              SEXM
298686       2022     2022           US  ...         CRDMEAN                       SEX              SEXM
299276       2022     2022           PA  ...         CRDMEAN                       SEX              SEXM
299557       2022     2022           SD  ...         CRDMEAN                       SEX              SEXM
299691       2022     2022           NC  ...         CRDMEAN                       SEX              SEXM
299750       2022     2022           OH  ...         CRDMEAN                       SEX              SEXM
301529       2022     2022           UT  ...         CRDMEAN                       SEX              SEXM
302880       2022     2022           NH  ...         CRDMEAN                       SEX              SEXM
303465       2022     2022           VI  ...         CRDMEAN                       SEX              SEXM
303820       2022     2022           VA  ...         CRDMEAN                       SEX              SEXM
304317       2022     2022           WI  ...         CRDMEAN                       SEX              SEXM
305741       2022     2022           VT  ...         CRDMEAN                       SEX              SEXM
305851       2022     2022           WY  ...         CRDMEAN                       SEX              SEXM
306574       2022     2022           WA  ...         CRDMEAN                       SEX              SEXM
308648       2022     2022           WV  ...         CRDMEAN                       SEX              SEXM

[55 rows x 22 columns]

In [9]:
state_data = mentalHealthMaleDF

mMale = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"],
    key_on="feature.id",
    fill_color="Blues",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among male adults in the U.S.",
).add_to(mMale)

folium.LayerControl().add_to(mMale)

mMale

- Data for Female Adults

In [ ]:
# Filter to show mean for females in the year 2022
mentalHealthFemaleDF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Female')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthFemaleDF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
264955       2022     2022           AL  ...         CRDMEAN                       SEX              SEXF
264987       2022     2022           CT  ...         CRDMEAN                       SEX              SEXF
266839       2022     2022           FL  ...         CRDMEAN                       SEX              SEXF
268302       2022     2022           AK  ...         CRDMEAN                       SEX              SEXF
269034       2022     2022           AR  ...         CRDMEAN                       SEX              SEXF
269992       2022     2022           AZ  ...         CRDMEAN                       SEX              SEXF
270857       2022     2022           DC  ...         CRDMEAN                       SEX              SEXF
271406       2022     2022           DE  ...         CRDMEAN                       SEX              SEXF
271476       2022     2022           GA  ...         CRDMEAN                       SEX              SEXF
272621       2022     2022           HI  ...         CRDMEAN                       SEX              SEXF
274635       2022     2022           CA  ...         CRDMEAN                       SEX              SEXF
274722       2022     2022           CO  ...         CRDMEAN                       SEX              SEXF
274766       2022     2022           GU  ...         CRDMEAN                       SEX              SEXF
276762       2022     2022           MD  ...         CRDMEAN                       SEX              SEXF
276885       2022     2022           MS  ...         CRDMEAN                       SEX              SEXF
277870       2022     2022           MT  ...         CRDMEAN                       SEX              SEXF
279840       2022     2022           KY  ...         CRDMEAN                       SEX              SEXF
280403       2022     2022           MI  ...         CRDMEAN                       SEX              SEXF
280443       2022     2022           ID  ...         CRDMEAN                       SEX              SEXF
280501       2022     2022           LA  ...         CRDMEAN                       SEX              SEXF
280593       2022     2022           NE  ...         CRDMEAN                       SEX              SEXF
282044       2022     2022           IN  ...         CRDMEAN                       SEX              SEXF
282109       2022     2022           IA  ...         CRDMEAN                       SEX              SEXF
283907       2022     2022           MA  ...         CRDMEAN                       SEX              SEXF
284271       2022     2022           NV  ...         CRDMEAN                       SEX              SEXF
285413       2022     2022           MO  ...         CRDMEAN                       SEX              SEXF
285781       2022     2022           MN  ...         CRDMEAN                       SEX              SEXF
287058       2022     2022           ME  ...         CRDMEAN                       SEX              SEXF
287550       2022     2022           KS  ...         CRDMEAN                       SEX              SEXF
288930       2022     2022           IL  ...         CRDMEAN                       SEX              SEXF
289860       2022     2022           NM  ...         CRDMEAN                       SEX              SEXF
292487       2022     2022           NY  ...         CRDMEAN                       SEX              SEXF
293272       2022     2022           SD  ...         CRDMEAN                       SEX              SEXF
293818       2022     2022           TN  ...         CRDMEAN                       SEX              SEXF
294974       2022     2022           TX  ...         CRDMEAN                       SEX              SEXF
295044       2022     2022           NJ  ...         CRDMEAN                       SEX              SEXF
297704       2022     2022           OK  ...         CRDMEAN                       SEX              SEXF
298186       2022     2022           ND  ...         CRDMEAN                       SEX              SEXF
298814       2022     2022           OR  ...         CRDMEAN                       SEX              SEXF
298838       2022     2022           US  ...         CRDMEAN                       SEX              SEXF
299178       2022     2022           RI  ...         CRDMEAN                       SEX              SEXF
300767       2022     2022           NH  ...         CRDMEAN                       SEX              SEXF
300965       2022     2022           NC  ...         CRDMEAN                       SEX              SEXF
301075       2022     2022           SC  ...         CRDMEAN                       SEX              SEXF
302606       2022     2022           PA  ...         CRDMEAN                       SEX              SEXF
302783       2022     2022           PR  ...         CRDMEAN                       SEX              SEXF
303038       2022     2022           OH  ...         CRDMEAN                       SEX              SEXF
303230       2022     2022           UT  ...         CRDMEAN                       SEX              SEXF
303412       2022     2022           WV  ...         CRDMEAN                       SEX              SEXF
306676       2022     2022           VT  ...         CRDMEAN                       SEX              SEXF
307388       2022     2022           VI  ...         CRDMEAN                       SEX              SEXF
307429       2022     2022           WY  ...         CRDMEAN                       SEX              SEXF
307801       2022     2022           VA  ...         CRDMEAN                       SEX              SEXF
307917       2022     2022           WA  ...         CRDMEAN                       SEX              SEXF
308214       2022     2022           WI  ...         CRDMEAN                       SEX              SEXF

[55 rows x 22 columns]

In [11]:
state_data = mentalHealthFemaleDF

mFemale = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"],
    key_on="feature.id",
    fill_color="Reds",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among female adults in the U.S.",
).add_to(mFemale)

folium.LayerControl().add_to(mFemale)

mFemale

- Data for Ages 18-44

In [ ]:
# Filter to show mean for adults aged 18-44 in the year 2022
mentalHealthAge18DF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Age 18-44')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthAge18DF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
961          2022     2022           KS  ...         CRDMEAN                       AGE           AGE1844
262303       2022     2022           AL  ...         CRDMEAN                       AGE           AGE1844
263023       2022     2022           AR  ...         CRDMEAN                       AGE           AGE1844
268679       2022     2022           CA  ...         CRDMEAN                       AGE           AGE1844
268856       2022     2022           GA  ...         CRDMEAN                       AGE           AGE1844
268960       2022     2022           DE  ...         CRDMEAN                       AGE           AGE1844
269141       2022     2022           AK  ...         CRDMEAN                       AGE           AGE1844
269706       2022     2022           DC  ...         CRDMEAN                       AGE           AGE1844
270945       2022     2022           CO  ...         CRDMEAN                       AGE           AGE1844
271408       2022     2022           AZ  ...         CRDMEAN                       AGE           AGE1844
271615       2022     2022           HI  ...         CRDMEAN                       AGE           AGE1844
272128       2022     2022           GU  ...         CRDMEAN                       AGE           AGE1844
273472       2022     2022           FL  ...         CRDMEAN                       AGE           AGE1844
273608       2022     2022           CT  ...         CRDMEAN                       AGE           AGE1844
278572       2022     2022           NE  ...         CRDMEAN                       AGE           AGE1844
278728       2022     2022           NV  ...         CRDMEAN                       AGE           AGE1844
280275       2022     2022           MO  ...         CRDMEAN                       AGE           AGE1844
282002       2022     2022           MT  ...         CRDMEAN                       AGE           AGE1844
282277       2022     2022           MD  ...         CRDMEAN                       AGE           AGE1844
282981       2022     2022           KY  ...         CRDMEAN                       AGE           AGE1844
283867       2022     2022           MS  ...         CRDMEAN                       AGE           AGE1844
284652       2022     2022           MN  ...         CRDMEAN                       AGE           AGE1844
285460       2022     2022           MI  ...         CRDMEAN                       AGE           AGE1844
285851       2022     2022           IN  ...         CRDMEAN                       AGE           AGE1844
286125       2022     2022           IA  ...         CRDMEAN                       AGE           AGE1844
287186       2022     2022           ME  ...         CRDMEAN                       AGE           AGE1844
287629       2022     2022           IL  ...         CRDMEAN                       AGE           AGE1844
287746       2022     2022           LA  ...         CRDMEAN                       AGE           AGE1844
287818       2022     2022           ID  ...         CRDMEAN                       AGE           AGE1844
288438       2022     2022           MA  ...         CRDMEAN                       AGE           AGE1844
289579       2022     2022           TX  ...         CRDMEAN                       AGE           AGE1844
290294       2022     2022           UT  ...         CRDMEAN                       AGE           AGE1844
290692       2022     2022           NM  ...         CRDMEAN                       AGE           AGE1844
290723       2022     2022           NH  ...         CRDMEAN                       AGE           AGE1844
291253       2022     2022           US  ...         CRDMEAN                       AGE           AGE1844
292566       2022     2022           OR  ...         CRDMEAN                       AGE           AGE1844
294815       2022     2022           TN  ...         CRDMEAN                       AGE           AGE1844
295856       2022     2022           SD  ...         CRDMEAN                       AGE           AGE1844
295926       2022     2022           ND  ...         CRDMEAN                       AGE           AGE1844
298006       2022     2022           NJ  ...         CRDMEAN                       AGE           AGE1844
298048       2022     2022           PA  ...         CRDMEAN                       AGE           AGE1844
298259       2022     2022           OK  ...         CRDMEAN                       AGE           AGE1844
298347       2022     2022           SC  ...         CRDMEAN                       AGE           AGE1844
298779       2022     2022           OH  ...         CRDMEAN                       AGE           AGE1844
298878       2022     2022           PR  ...         CRDMEAN                       AGE           AGE1844
299182       2022     2022           NY  ...         CRDMEAN                       AGE           AGE1844
299738       2022     2022           RI  ...         CRDMEAN                       AGE           AGE1844
302469       2022     2022           NC  ...         CRDMEAN                       AGE           AGE1844
304059       2022     2022           VA  ...         CRDMEAN                       AGE           AGE1844
305437       2022     2022           WY  ...         CRDMEAN                       AGE           AGE1844
305572       2022     2022           WI  ...         CRDMEAN                       AGE           AGE1844
306973       2022     2022           WA  ...         CRDMEAN                       AGE           AGE1844
307057       2022     2022           VI  ...         CRDMEAN                       AGE           AGE1844
307626       2022     2022           VT  ...         CRDMEAN                       AGE           AGE1844
307865       2022     2022           WV  ...         CRDMEAN                       AGE           AGE1844

[55 rows x 22 columns]

In [13]:
state_data = mentalHealthAge18DF

mAge18 = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"],
    key_on="feature.id",
    fill_color="YlGnBu",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among adults in the U.S. between ages 18-44.",
).add_to(mAge18)

folium.LayerControl().add_to(mAge18)

mAge18

- Data for Ages 45-64

In [ ]:
# Filter to show mean for adults aged 45-64 in the year 2022
mentalHealthAge45DF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Age 45-64')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthAge45DF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
1028         2022     2022           OK  ...         CRDMEAN                       AGE           AGE4564
261964       2022     2022           GU  ...         CRDMEAN                       AGE           AGE4564
262702       2022     2022           HI  ...         CRDMEAN                       AGE           AGE4564
264591       2022     2022           DC  ...         CRDMEAN                       AGE           AGE4564
264647       2022     2022           CA  ...         CRDMEAN                       AGE           AGE4564
264772       2022     2022           DE  ...         CRDMEAN                       AGE           AGE4564
265461       2022     2022           AL  ...         CRDMEAN                       AGE           AGE4564
266696       2022     2022           CO  ...         CRDMEAN                       AGE           AGE4564
266799       2022     2022           AR  ...         CRDMEAN                       AGE           AGE4564
268314       2022     2022           CT  ...         CRDMEAN                       AGE           AGE4564
268671       2022     2022           GA  ...         CRDMEAN                       AGE           AGE4564
270154       2022     2022           FL  ...         CRDMEAN                       AGE           AGE4564
272766       2022     2022           AK  ...         CRDMEAN                       AGE           AGE4564
274651       2022     2022           AZ  ...         CRDMEAN                       AGE           AGE4564
276625       2022     2022           MN  ...         CRDMEAN                       AGE           AGE4564
278699       2022     2022           IA  ...         CRDMEAN                       AGE           AGE4564
279420       2022     2022           KS  ...         CRDMEAN                       AGE           AGE4564
279891       2022     2022           ME  ...         CRDMEAN                       AGE           AGE4564
281245       2022     2022           MI  ...         CRDMEAN                       AGE           AGE4564
282087       2022     2022           NV  ...         CRDMEAN                       AGE           AGE4564
282191       2022     2022           MO  ...         CRDMEAN                       AGE           AGE4564
282892       2022     2022           IN  ...         CRDMEAN                       AGE           AGE4564
283175       2022     2022           ID  ...         CRDMEAN                       AGE           AGE4564
283724       2022     2022           NE  ...         CRDMEAN                       AGE           AGE4564
284297       2022     2022           MA  ...         CRDMEAN                       AGE           AGE4564
284821       2022     2022           IL  ...         CRDMEAN                       AGE           AGE4564
284920       2022     2022           LA  ...         CRDMEAN                       AGE           AGE4564
284943       2022     2022           MT  ...         CRDMEAN                       AGE           AGE4564
286088       2022     2022           MD  ...         CRDMEAN                       AGE           AGE4564
286774       2022     2022           MS  ...         CRDMEAN                       AGE           AGE4564
286798       2022     2022           KY  ...         CRDMEAN                       AGE           AGE4564
291056       2022     2022           TN  ...         CRDMEAN                       AGE           AGE4564
291320       2022     2022           NM  ...         CRDMEAN                       AGE           AGE4564
292835       2022     2022           RI  ...         CRDMEAN                       AGE           AGE4564
293175       2022     2022           NY  ...         CRDMEAN                       AGE           AGE4564
293246       2022     2022           NH  ...         CRDMEAN                       AGE           AGE4564
294507       2022     2022           OH  ...         CRDMEAN                       AGE           AGE4564
295048       2022     2022           OR  ...         CRDMEAN                       AGE           AGE4564
295058       2022     2022           PR  ...         CRDMEAN                       AGE           AGE4564
295758       2022     2022           UT  ...         CRDMEAN                       AGE           AGE4564
296063       2022     2022           PA  ...         CRDMEAN                       AGE           AGE4564
298261       2022     2022           NJ  ...         CRDMEAN                       AGE           AGE4564
298842       2022     2022           ND  ...         CRDMEAN                       AGE           AGE4564
299637       2022     2022           NC  ...         CRDMEAN                       AGE           AGE4564
300058       2022     2022           SD  ...         CRDMEAN                       AGE           AGE4564
301283       2022     2022           TX  ...         CRDMEAN                       AGE           AGE4564
302505       2022     2022           SC  ...         CRDMEAN                       AGE           AGE4564
303041       2022     2022           US  ...         CRDMEAN                       AGE           AGE4564
303324       2022     2022           WV  ...         CRDMEAN                       AGE           AGE4564
303950       2022     2022           VI  ...         CRDMEAN                       AGE           AGE4564
304755       2022     2022           WA  ...         CRDMEAN                       AGE           AGE4564
306052       2022     2022           VT  ...         CRDMEAN                       AGE           AGE4564
306771       2022     2022           WI  ...         CRDMEAN                       AGE           AGE4564
306811       2022     2022           WY  ...         CRDMEAN                       AGE           AGE4564
308796       2022     2022           VA  ...         CRDMEAN                       AGE           AGE4564

[55 rows x 22 columns]

In [15]:
state_data = mentalHealthAge45DF

mAge45 = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"],
    key_on="feature.id",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among adults in the U.S. between ages 45-64.",
).add_to(mAge45)

folium.LayerControl().add_to(mAge45)

mAge45

- Data for Ages 65+

In [ ]:
# Filter to show mean for adults aged 65+ in the year 2022
mentalHealthAge65DF = diseaseDF[(diseaseDF['Question'] == 'Average mentally unhealthy days among adults')&\
    (diseaseDF['DataValueType'] == 'Crude Mean') & (diseaseDF['Stratification1'] == 'Age >=65')&\
    (diseaseDF['YearStart'] == 2022)]
mentalHealthAge65DF

        YearStart  YearEnd LocationAbbr  ... DataValueTypeID StratificationCategoryID1 StratificationID1
262630       2022     2022           FL  ...         CRDMEAN                       AGE            AGE65P
263387       2022     2022           CT  ...         CRDMEAN                       AGE            AGE65P
264638       2022     2022           CA  ...         CRDMEAN                       AGE            AGE65P
265357       2022     2022           AK  ...         CRDMEAN                       AGE            AGE65P
268436       2022     2022           HI  ...         CRDMEAN                       AGE            AGE65P
268796       2022     2022           CO  ...         CRDMEAN                       AGE            AGE65P
269387       2022     2022           GU  ...         CRDMEAN                       AGE            AGE65P
271587       2022     2022           GA  ...         CRDMEAN                       AGE            AGE65P
272139       2022     2022           DE  ...         CRDMEAN                       AGE            AGE65P
272851       2022     2022           DC  ...         CRDMEAN                       AGE            AGE65P
272919       2022     2022           AL  ...         CRDMEAN                       AGE            AGE65P
274966       2022     2022           AR  ...         CRDMEAN                       AGE            AGE65P
274989       2022     2022           AZ  ...         CRDMEAN                       AGE            AGE65P
275234       2022     2022           IA  ...         CRDMEAN                       AGE            AGE65P
275648       2022     2022           MO  ...         CRDMEAN                       AGE            AGE65P
277142       2022     2022           IN  ...         CRDMEAN                       AGE            AGE65P
277171       2022     2022           IL  ...         CRDMEAN                       AGE            AGE65P
277865       2022     2022           NE  ...         CRDMEAN                       AGE            AGE65P
278091       2022     2022           NV  ...         CRDMEAN                       AGE            AGE65P
278158       2022     2022           ID  ...         CRDMEAN                       AGE            AGE65P
278439       2022     2022           MA  ...         CRDMEAN                       AGE            AGE65P
280079       2022     2022           KY  ...         CRDMEAN                       AGE            AGE65P
280249       2022     2022           MD  ...         CRDMEAN                       AGE            AGE65P
283554       2022     2022           MN  ...         CRDMEAN                       AGE            AGE65P
284042       2022     2022           MT  ...         CRDMEAN                       AGE            AGE65P
285424       2022     2022           MS  ...         CRDMEAN                       AGE            AGE65P
286216       2022     2022           MI  ...         CRDMEAN                       AGE            AGE65P
286960       2022     2022           LA  ...         CRDMEAN                       AGE            AGE65P
287008       2022     2022           KS  ...         CRDMEAN                       AGE            AGE65P
287840       2022     2022           ME  ...         CRDMEAN                       AGE            AGE65P
291180       2022     2022           NC  ...         CRDMEAN                       AGE            AGE65P
291374       2022     2022           ND  ...         CRDMEAN                       AGE            AGE65P
292478       2022     2022           SD  ...         CRDMEAN                       AGE            AGE65P
293610       2022     2022           NM  ...         CRDMEAN                       AGE            AGE65P
293722       2022     2022           TX  ...         CRDMEAN                       AGE            AGE65P
294206       2022     2022           NJ  ...         CRDMEAN                       AGE            AGE65P
295152       2022     2022           PA  ...         CRDMEAN                       AGE            AGE65P
295981       2022     2022           SC  ...         CRDMEAN                       AGE            AGE65P
297121       2022     2022           PR  ...         CRDMEAN                       AGE            AGE65P
297747       2022     2022           US  ...         CRDMEAN                       AGE            AGE65P
299487       2022     2022           TN  ...         CRDMEAN                       AGE            AGE65P
300396       2022     2022           RI  ...         CRDMEAN                       AGE            AGE65P
300711       2022     2022           UT  ...         CRDMEAN                       AGE            AGE65P
301171       2022     2022           OH  ...         CRDMEAN                       AGE            AGE65P
301550       2022     2022           NH  ...         CRDMEAN                       AGE            AGE65P
301677       2022     2022           OR  ...         CRDMEAN                       AGE            AGE65P
302431       2022     2022           NY  ...         CRDMEAN                       AGE            AGE65P
302574       2022     2022           OK  ...         CRDMEAN                       AGE            AGE65P
303460       2022     2022           WY  ...         CRDMEAN                       AGE            AGE65P
304328       2022     2022           WI  ...         CRDMEAN                       AGE            AGE65P
306044       2022     2022           VA  ...         CRDMEAN                       AGE            AGE65P
308364       2022     2022           WA  ...         CRDMEAN                       AGE            AGE65P
308452       2022     2022           VT  ...         CRDMEAN                       AGE            AGE65P
308600       2022     2022           VI  ...         CRDMEAN                       AGE            AGE65P
309026       2022     2022           WV  ...         CRDMEAN                       AGE            AGE65P

[55 rows x 22 columns]

In [17]:
state_data = mentalHealthAge65DF

mAge65 = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["LocationAbbr", "DataValue"],
    key_on="feature.id",
    fill_color="Purples",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average number of mentally unhealthy days among adults in the U.S. aged 65 or older.",
).add_to(mAge65)

folium.LayerControl().add_to(mAge65)

mAge65

# Results